### ISSUE TITLE
[BUG] invalid UUID length: 0

### ISSUE THREAD

**Issue by ahloul** [hibiken/asynq#645]
panic: uuid: Parse(): invalid UUID length: 0

goroutine 58 [running]:
github.com/google/uuid.MustParse(0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/google/uuid@v1.3.0/uuid.go:163 +0x125
github.com/hibiken/asynq/internal/base.DecodeMessage(0x1d165d0, 0x0, 0x0, 0x1d165d0, 0x0, 0x0)
	/go/pkg/mod/github.com/hibiken/asynq@v0.18.4/internal/base/base.go:264 +0x105
github.com/hibiken/asynq/internal/rdb.(*RDB).ListDeadlineExceeded(0xc00051a8c0, 0xc10712fa2e27c1f2, 0xfffffff90507b7ab, 0x1ce79e0, 0xc000532e80, 0x3, 0x4, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/hibiken/asynq@v0.18.4/internal/rdb/rdb.go:679 +0x3fe
github.com/hibiken/asynq.(*recoverer).recover(0xc00051c910)
	/go/pkg/mod/github.com/hibiken/asynq@v0.18.4/recoverer.go:79 +0x8d
github.com/hibiken/asynq.(*recoverer).start.func1(0xc00027c170, 0xc00051c910)
	/go/pkg/mod/github.com/hibiken/asynq@v0.18.4/recoverer.go:60 +0x6e
created by github.com/hibiken/asynq.(*recoverer).start

**Comment by bfwbbrj** [comment]
Can you try using the latest version of asynq and see if the issue persists?
